
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761}/eureka
    instance:
      hostname: localhost