
application:
  fileName: iam-service-test.yml
  env: ${spring.profiles.active}
  secretKey: c93a3a8c-6226-45d7-90e8-b673bd1e4aeb
  tokenExpireInMin: 10

spring:
  data:
    mongodb:
      uri: mongodb+srv://edutest-dbuser:edutest-dbuser@test.s2cen.mongodb.net/iam-service?retryWrites=true&w=majority
      auto-index-creation: true
