
application:
  message: Configured by Azure Spring Cloud (IAM-dev)

server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://edutest-dbuser:edutest-dbuser@cluster0.s2cen.mongodb.net/iam-service?retryWrites=true&w=majority
      # host: localhost
      # port: 27017
      # database: IAM-SERVICE