
application:
  message: Configured by Azure Spring Cloud (IAM-dev)

server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://edutest-dbuser:edutest-dbuser@cluster0.s2cen.mongodb.net/iam-service-dev?retryWrites=true&w=majority
